[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
