[deps]
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
