[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashBase = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DateFormats = "44557152-fe0a-4de1-8405-416d90313ce6"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxAtmosphericModels = "5718ef0a-a30f-426d-bcd9-4cf31dd12909"
SatelliteToolboxGeomagneticField = "9fc549ba-b5d7-49a2-b268-8171e5fb6e89"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
